name: Build and Publish Golang Alpine Image

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'dockerfiles/golang/alpine/Dockerfile'
  #     - '.github/workflows/golang-alpine.yml'
  # schedule:
  #   # This schedule runs at 02:00 AM UTC every day.
  #   - cron: '0 2 * * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      DOCKERFILE_PATH: 'dockerfiles/golang/alpine/Dockerfile'
      IMAGE_NAME: 'golang-alpine'
      IMAGE_ARCH: 'linux/amd64'

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.IMAGE_ARCH }}

      - uses: docker/setup-buildx-action@v3
        with:
          install: true
          use: true

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          platforms: ${{ env.IMAGE_ARCH }}
          provenance: false
