name: Build and Publish LLaMA Box image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'LLaMA Box tag to build'
        required: true
        default: 'v0.0.127'
      arch:
        description: 'Target arch of image'
        required: true
        type: choice
        options:
          - linux/amd64
      type:
        description: 'Type of image'
        required: true
        type: choice
        options:
          - CPU-AVX2
          - CPU-AVX512
          - VULKAN
          - CUDA

jobs:
  build-and-push:
    name: Build ${{ github.event.inputs.type }} for ${{ github.event.inputs.arch }} (${{ github.event.inputs.tag }})
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: 'llama-box'

    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        run: echo "IMAGE_TAG=${{ github.event.inputs.type }}-${{ github.event.inputs.arch }}-${{ github.event.inputs.tag }}" | sed 's|/|-|g' >> $GITHUB_ENV

      - uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ github.event.inputs.arch }}

      - uses: docker/setup-buildx-action@v3
        with:
          install: true
          use: true

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: "dockerfiles/llama-box/${{ github.event.inputs.arch }}/Dockerfile.${{ github.event.inputs.type }}"
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          platforms: ${{ github.event.inputs.arch }}
          provenance: false
          build-args: |
            LLAMA_BOX_TAG=${{ github.event.inputs.tag }}
