name: Build and Publish vLLM image

on:
  workflow_dispatch:
    inputs:
      vllm_repo:
        description: 'vLLM repository URL'
        required: true
        default: 'https://github.com/vllm-project/vllm.git'
      vllm_branch:
        description: 'vLLM branch to build'
        required: true
        default: 'main'
      arch:
        description: 'Target arch of image'
        required: true
        type: choice
        options:
          - linux/amd64
      type:
        description: 'Type of image'
        required: true
        type: choice
        options:
          - rocm

jobs:
  build-and-push:
    name: Build ${{ github.event.inputs.type }} for ${{ github.event.inputs.arch }} (${{ github.event.inputs.vllm_branch }})
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: 'vllm'

    steps:
      - uses: actions/checkout@v4

      - name: Free disk space
        run: |
          echo "Available disk space before cleanup:"
          df -h
          # Remove unnecessary packages and files
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/share/swift
          sudo rm -rf /opt/hostedtoolcache
          # Clean up Docker
          docker system prune -af
          echo "Available disk space after cleanup:"
          df -h

      - name: Set image tag
        run: echo "IMAGE_TAG=${{ github.event.inputs.type }}-${{ github.event.inputs.arch }}-${{ github.event.inputs.vllm_branch }}" | sed 's|/|-|g' >> $GITHUB_ENV

      - uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ github.event.inputs.arch }}

      - uses: docker/setup-buildx-action@v3
        with:
          install: true
          use: true

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: "dockerfiles/vllm/Dockerfile.${{ github.event.inputs.type }}"
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          platforms: ${{ github.event.inputs.arch }}
          provenance: false
          build-args: |
            VLLM_REPO=${{ github.event.inputs.vllm_repo }}
            VLLM_BRANCH=${{ github.event.inputs.vllm_branch }}
            REMOTE_VLLM=1
          cache-from: type=gha
          cache-to: type=gha,mode=max